### ISSUE TITLE
Reports 'Missing positive glob' When Gulp with ! directive

### ISSUE THREAD

**Issue by bartmao** [bartmao/BartMaoChatRoom#4]
```
    var stream2 = gulp.src([
        '!src/client/html/*.ts'
    ]).pipe(gulp.dest('build/client'));

```

Details

> [15:16:25] Error: Missing positive glob
>     at Object.gs.create (C:\Users\bmao002\Desktop\Projects\BartMaoChatRoom\node_
> modules\glob-stream\index.js:73:39)
>     at Gulp.src (C:\Users\bmao002\Desktop\Projects\BartMaoChatRoom\node_modules\
> vinyl-fs\lib\src\index.js:33:23)
>     at build (C:\Users\bmao002\Desktop\Projects\BartMaoChatRoom\gulpfile.js:35:2
> 4)
>     at Gulp.<anonymous> (C:\Users\bmao002\Desktop\Projects\BartMaoChatRoom\gulpf
> ile.js:12:5)
>     at module.exports (C:\Users\bmao002\Desktop\Projects\BartMaoChatRoom\node_mo
> dules\orchestrator\lib\runTask.js:34:7)
>     at Gulp.Orchestrator._runTask (C:\Users\bmao002\Desktop\Projects\BartMaoChat
> Room\node_modules\orchestrator\index.js:273:3)
>     at Gulp.Orchestrator._runStep (C:\Users\bmao002\Desktop\Projects\BartMaoChat
> Room\node_modules\orchestrator\index.js:214:10)
>     at Gulp.Orchestrator.start (C:\Users\bmao002\Desktop\Projects\BartMaoChatRoo
> m\node_modules\orchestrator\index.js:134:8)
>     at C:\Users\bmao002\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\
> ^3.7.0\index.js:46:20
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)

**Comment by bartmao** [comment]
See explanation of this ! directive in official  API document:

> A glob that begins with ! excludes matching files **from the glob results** up to that point. For example, consider this directory structure:

So we need change the code like that:

```
    var stream2 = gulp.src([
        'src/client/html/*.*',
        '!src/client/html/*.ts'
    ]).pipe(gulp.dest('build/client'));
```
